# Generated by Django 4.0.4 on 2022-07-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentSerializer',
            new_name='Student',
        ),
    ]
