# Generated by Django 4.0.4 on 2022-08-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.BigIntegerField(max_length=10)),
            ],
        ),
    ]
