# Generated by Django 4.0.4 on 2022-08-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageUserApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='FirstName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='LastName',
            new_name='password',
        ),
    ]
