# Generated by Django 4.0.4 on 2022-08-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageUserApi', '0002_rename_firstname_usermodel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='password',
            new_name='LastName',
        ),
    ]
